@Library("my-shared-library") _
pipeline {
  agent none
  stages {
    stage('Testing for Maven') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh '''
          # Ensure Maven is installed
          mvn --version
          
          # the shared library for java
          Java()
          
          # Compile and run the Java program
          javac SimpleMath.java
          java SimpleMath
        '''
      }
    }
    stage('Testing for Node.js') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh '''
          # Ensure Node.js and npm are installed
          node --version
          npm --version

          # shared library for node.js
          Nodejs()
          > math.js
          # Run the Node.js program
          node math.js
        '''
      }
    }
    stage('Testing for Python') {
      agent {
        docker { image 'python:latest' }
      }
      steps {
        sh '''
          # Ensure Python is installed
          python --version
          
          # shared library for python
          Python()
          
          # Run the Python program
          python math.py
        '''
      }
    }
  }
}
