pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh '''public class SimpleMath {
    public static void main(String[] args) {
        int num1 = 10; // First number
        int num2 = 5;  // Second number

        // Perform addition and subtraction
        int sum = num1 + num2;
        int difference = num1 - num2;

        // Display the results
        System.out.println("Addition: " + sum);
        System.out.println("Subtraction: " + difference);
    }
}
'''
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh '''// Define two numbers
const num1 = 10; // First number
const num2 = 5;  // Second number

// Perform addition and subtraction
const sum = num1 + num2;
const difference = num1 - num2;

// Display the results
console.log(`Addition: ${sum}`);
console.log(`Subtraction: ${difference}`);

'''
      }
    }
  }
}
